apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/chatplatform-app-network: "true"
        io.kompose.service: app
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - "sh /app/entrypoint.sh"
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@db/mydatabase
            - name: DOCUMENT_STORAGE_PATH
              value: /app/documents
            - name: RABBITMQ_URL
              value: amqp://user:password@rabbitmq/%2F
          image: sirgrigor/app:latest
          name: app
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/data
              name: app-claim0
      restartPolicy: Always
      volumes:
        - name: app-claim0
          persistentVolumeClaim:
            claimName: app-claim0
