version: '3.8'

services:
  app:
    build:
      context: .
    image: app:latest
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - db
    environment:
      RABBITMQ_URL: amqp://user:password@rabbitmq/%2F
      DATABASE_URL: postgresql://postgres:postgres@db/mydatabase
      DOCUMENT_STORAGE_PATH: /app/documents
    volumes:
      - .:/app
    entrypoint: [ "/app/entrypoint.sh" ]
    networks:
      - app_network

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    name: chatplatform_app_network
    driver: bridge

volumes:
  postgres_data: { }
