"""Initial m1igrati1111

Revision ID: 4f0c5e1bb0dc
Revises: 9f733d7c5c75
Create Date: 2024-02-04 11:24:50.726281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f0c5e1bb0dc'
down_revision: Union[str, None] = '9f733d7c5c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
