"""Initial migration1

Revision ID: 6f9be07a00ab
Revises: e0ebdd1024d8
Create Date: 2024-02-07 09:53:35.960748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9be07a00ab'
down_revision: Union[str, None] = 'e0ebdd1024d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'document_content')
    # ### end Alembic commands ###
