"""Initial m1igrati11111111

Revision ID: 71abc08c6f4e
Revises: 92677f35c2c6
Create Date: 2024-02-05 19:13:11.491710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71abc08c6f4e'
down_revision: Union[str, None] = '92677f35c2c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('response_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'response_id')
    # ### end Alembic commands ###
