"""Initial migration111

Revision ID: 78082ac5617a
Revises: aa23e023d213
Create Date: 2024-02-07 10:44:11.742163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78082ac5617a'
down_revision: Union[str, None] = 'aa23e023d213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_metadata', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'document_metadata')
    # ### end Alembic commands ###
