"""Initial migrati11

Revision ID: ee29416f1e76
Revises: 7ea660b9a80b
Create Date: 2024-02-02 22:01:49.857613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee29416f1e76'
down_revision: Union[str, None] = '7ea660b9a80b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('courses_widget_token_key', 'courses', type_='unique')
    op.drop_column('courses', 'widget_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('widget_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('courses_widget_token_key', 'courses', ['widget_token'])
    # ### end Alembic commands ###
