"""Prepare for new baseline4

Revision ID: 15ad759708bf
Revises: e9bcc16968b1
Create Date: 2024-02-27 11:36:13.183895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15ad759708bf'
down_revision: Union[str, None] = 'e9bcc16968b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('doc_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'doc_id')
    # ### end Alembic commands ###
